// <auto-generated />
namespace MachineLearningBP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeIncidentExampleResultFromDoubleToInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeIncidentExampleResultFromDoubleToInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201710261712142_ChangeIncidentExampleResultFromDoubleToInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
